# Generated by Django 6.0.6 on 2026-06-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('tmdb', 'TMDB'), ('xtream', 'Xtream')], default='tmdb', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
