# Generated by Django 6.0.6 on 2026-06-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='last_tmdb_movie_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='last_tmdb_series_page',
            field=models.IntegerField(default=1),
        ),
    ]
