# Generated by Django 6.0.6 on 2026-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_last_tmdb_movie_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='items_per_row',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (6, '6')], default=3),
        ),
    ]
