# Generated by Django 6.0.6 on 2026-06-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_items_per_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='card_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
    ]
