# Generated by Django 6.0.6 on 2026-06-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_card_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_sidebar_ads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_ads_code',
            field=models.TextField(blank=True, help_text='HTML/JS code for sidebar ads', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'Extra Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='title_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'Extra Large')], default='medium', max_length=10),
        ),
    ]
