# Generated by Django 6.0.6 on 2026-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_enable_sidebar_ads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='last_tmdb_movies_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='last_tmdb_series_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
