# Generated by Django 6.0.6 on 2026-06-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_last_tmdb_movies_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_color',
            field=models.CharField(default='#e50914', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='NETFLIX', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_tagline',
            field=models.CharField(default='Unlimited movies, TV shows, and more', max_length=200),
        ),
    ]
