# Generated by Django 6.0.6 on 2026-06-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_brand_color_sitesettings_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=10)),
            ],
            options={
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='ContentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('movie', 'Movies'), ('tv', 'TV Shows')], max_length=10)),
                ('row_type', models.CharField(choices=[('popular', 'Popular'), ('top_rated', 'Top Rated'), ('upcoming', 'Upcoming (Movies)'), ('now_playing', 'Now Playing (Movies)'), ('on_the_air', 'On The Air (TV)'), ('airing_today', 'Airing Today (TV)'), ('genre', 'By Genre'), ('custom', 'Custom Filter')], default='popular', max_length=20)),
                ('sort_by', models.CharField(blank=True, default='popularity.desc', help_text='TMDB sort parameter, e.g., popularity.desc, vote_average.desc', max_length=50)),
                ('filter_params', models.TextField(blank=True, help_text='Additional TMDB filter params in JSON format, e.g., {"vote_average.gte": 7}')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genre')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
