# Generated by Django 6.0.6 on 2026-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_genre_contentrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrow',
            name='items_per_page',
            field=models.IntegerField(default=20, help_text='Number of items to load per page for this row'),
        ),
    ]
