# Generated by Django 6.0.6 on 2026-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contentrow_items_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrow',
            name='language',
            field=models.CharField(blank=True, help_text='TMDB language (e.g., en-US, es-ES, fr-FR)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contentrow',
            name='region',
            field=models.CharField(blank=True, help_text='TMDB region (e.g., US, GB, IN, FR)', max_length=10, null=True),
        ),
    ]
