# Generated by Django 6.0.6 on 2026-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contentrow_language_contentrow_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='core.genre'),
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='series', to='core.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stream_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_id',
            field=models.IntegerField(unique=True),
        ),
    ]
