# Generated by Django 6.0.6 on 2026-06-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_movie_genres_series_genres_alter_movie_stream_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='series',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='contentrow',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='TVChannel',
        ),
        migrations.DeleteModel(
            name='XtreamAccount',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='last_tmdb_movie_page',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='last_tmdb_movies_update',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='last_tmdb_series_page',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='last_tmdb_series_update',
        ),
        migrations.AddField(
            model_name='contentrow',
            name='genre_tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
