# Generated by Django 6.0.6 on 2026-06-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_genre_unique_together_remove_series_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blocked_urls',
            field=models.TextField(blank=True, help_text="List of URLs to block (one per line), or 'all' to block all except admin", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_url_blocking',
            field=models.BooleanField(default=False, help_text='Enable URL blocking for non-admin pages'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='redirect_url',
            field=models.CharField(blank=True, default='/', help_text='URL to redirect blocked requests to', max_length=200, null=True),
        ),
    ]
