# Generated by Django 6.0.6 on 2026-06-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_blocked_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='Email host (e.g., smtp.gmail.com)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Email app password (not regular Gmail password)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='Email address (e.g., your@gmail.com)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, help_text='Email port (e.g., 587 for TLS)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for email'),
        ),
    ]
