# Generated by Django 6.0.6 on 2026-06-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='watch_region',
            field=models.CharField(blank=True, default='US', help_text='TMDB watch region (e.g., US, GB, IN, FR)', max_length=10, null=True),
        ),
    ]
