# Generated by Django 6.0.6 on 2026-06-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesettings_watch_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='curated_top_movie_ids',
            field=models.TextField(blank=True, help_text='Comma-separated TMDB IDs of top movies (e.g., 123,456,789)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='curated_top_series_ids',
            field=models.TextField(blank=True, help_text='Comma-separated TMDB IDs of top series (e.g., 123,456,789)', null=True),
        ),
    ]
