# Generated by Django 6.0.6 on 2026-06-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings_curated_top_movie_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrow',
            name='auto_scroll',
            field=models.BooleanField(default=False, help_text='Enable auto-scrolling for this row on the homepage'),
        ),
    ]
