# Generated by Django 6.0.6 on 2026-06-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contentrow_auto_scroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(choices=[('system-ui', 'System UI'), ('Arial, sans-serif', 'Arial'), ('Helvetica, sans-serif', 'Helvetica'), ('"Segoe UI", sans-serif', 'Segoe UI'), ('Georgia, serif', 'Georgia'), ('"Times New Roman", serif', 'Times New Roman'), ('"Courier New", monospace', 'Courier New')], default='system-ui', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_style',
            field=models.CharField(choices=[('netflix', 'Netflix (Dark Red)'), ('amazon', 'Amazon Prime (Dark Blue)'), ('hbo', 'HBO Max (Dark Purple)'), ('disney', 'Disney+ (Dark Blue/Teal)'), ('spotify', 'Spotify (Dark Green)')], default='netflix', max_length=20),
        ),
    ]
