# Generated by Django 6.0.6 on 2026-06-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sitesettings_font_family_sitesettings_theme_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDBMovie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('belongs_to_collection', models.JSONField(blank=True, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('production_companies', models.JSONField(blank=True, null=True)),
                ('production_countries', models.JSONField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('spoken_languages', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TMDB Movie',
                'verbose_name_plural': 'TMDB Movies',
                'ordering': ('-popularity',),
            },
        ),
        migrations.CreateModel(
            name='TMDBTV',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.JSONField(blank=True, null=True)),
                ('episode_run_time', models.JSONField(blank=True, null=True)),
                ('first_air_date', models.CharField(blank=True, max_length=20, null=True)),
                ('genres', models.JSONField(blank=True, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('in_production', models.BooleanField(default=False)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('last_air_date', models.CharField(blank=True, max_length=20, null=True)),
                ('last_episode_to_air', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('next_episode_to_air', models.JSONField(blank=True, null=True)),
                ('networks', models.JSONField(blank=True, null=True)),
                ('number_of_episodes', models.IntegerField(blank=True, null=True)),
                ('number_of_seasons', models.IntegerField(blank=True, null=True)),
                ('origin_country', models.JSONField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('production_companies', models.JSONField(blank=True, null=True)),
                ('production_countries', models.JSONField(blank=True, null=True)),
                ('seasons', models.JSONField(blank=True, null=True)),
                ('spoken_languages', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TMDB TV Show',
                'verbose_name_plural': 'TMDB TV Shows',
                'ordering': ('-popularity',),
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='data_source',
            field=models.CharField(choices=[('tmdb', 'TMDB'), ('local', 'Local Database'), ('xtream', 'Xtream')], default='tmdb', max_length=10),
        ),
        migrations.CreateModel(
            name='TMDBGenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], max_length=10)),
            ],
            options={
                'verbose_name': 'TMDB Genre',
                'verbose_name_plural': 'TMDB Genres',
                'unique_together': {('id', 'media_type')},
            },
        ),
    ]
