# Generated by Django 6.0.6 on 2026-06-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tmdbmovie_tmdbtv_alter_sitesettings_data_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to identify this player configuration', max_length=100)),
                ('media_type', models.CharField(choices=[('movie', 'Movies'), ('tv', 'TV Shows'), ('both', 'Both')], default='both', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('order', models.IntegerField(default=0, help_text='Display order for dropdown')),
                ('player_color', models.CharField(blank=True, help_text='Primary color (hex without #, e.g., e50914)', max_length=10, null=True)),
                ('auto_play', models.BooleanField(default=False, help_text='Enable auto-play feature')),
                ('next_episode', models.BooleanField(default=False, help_text='Show next episode button (TV only)')),
                ('episode_selector', models.BooleanField(default=False, help_text='Enable episode selection menu (TV only)')),
                ('player_width', models.CharField(default='100%', help_text='Player width (e.g., 100%, 800px)', max_length=20)),
                ('player_height', models.CharField(default='600px', help_text='Player height (e.g., 600px, 100%)', max_length=20)),
                ('frameborder', models.IntegerField(default=0, help_text='iframe frameborder attribute')),
                ('allowfullscreen', models.BooleanField(default=True, help_text='Enable fullscreen mode')),
            ],
            options={
                'verbose_name': 'Player Configuration',
                'verbose_name_plural': 'Player Configurations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='active_movie_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_settings', to='core.playerconfiguration'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='active_tv_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv_settings', to='core.playerconfiguration'),
        ),
    ]
