# Generated by Django 6.0.6 on 2026-06-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_playerconfiguration_sitesettings_active_movie_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerconfiguration',
            name='custom_iframe_url',
            field=models.TextField(blank=True, help_text='Custom iframe URL (overrides Vidking). Use placeholders: {tmdb_id}, {season}, {episode}', null=True),
        ),
    ]
