# Generated by Django 6.0.6 on 2026-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='data_source',
            field=models.CharField(choices=[('tmdb', 'TMDB API'), ('tmdb_db', 'TMDB Database (Extracted)'), ('local', 'Local Database'), ('xtream', 'Xtream')], default='tmdb', max_length=10),
        ),
    ]
