# Generated by Django 6.0.6 on 2026-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_sitesettings_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDBApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='TMDB API Key', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this API key active and usable?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tmdb_db_host',
            field=models.CharField(blank=True, default='localhost', help_text='TMDB Database Host', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tmdb_db_name',
            field=models.CharField(blank=True, default='tmdb', help_text='TMDB Database Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tmdb_db_password',
            field=models.CharField(blank=True, default='tmdb123!', help_text='TMDB Database Password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tmdb_db_port',
            field=models.IntegerField(blank=True, default=5432, help_text='TMDB Database Port', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tmdb_db_user',
            field=models.CharField(blank=True, default='tmdb', help_text='TMDB Database User', max_length=255, null=True),
        ),
    ]
