# Generated by Django 6.0.6 on 2026-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_tmdbapikey_sitesettings_tmdb_db_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hide_live_tv',
            field=models.BooleanField(default=True, help_text='Hide Live TV from navigation'),
        ),
    ]
