# Generated by Django 6.0.6 on 2026-06-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sitesettings_hide_live_tv'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name in navbar', max_length=100)),
                ('item_type', models.CharField(choices=[('built_in', 'Built-in Item'), ('custom', 'Custom Button')], default='built_in', max_length=20)),
                ('built_in_id', models.CharField(blank=True, help_text="ID for built-in items like 'home', 'movies', etc.", max_length=50, null=True)),
                ('url', models.CharField(blank=True, help_text='URL for custom items', max_length=255, null=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-home')", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this item in navbar')),
                ('order', models.IntegerField(default=0, help_text='Display order in navbar')),
                ('dropdown_items', models.JSONField(blank=True, help_text='JSON array of dropdown items (for dropdown menus)', null=True)),
            ],
            options={
                'verbose_name_plural': 'Navbar Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
