# Generated by Django 6.0.6 on 2026-06-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_navbaritem'),
    ]

    operations = [
    ]
