# Generated by Django 6.0.6 on 2026-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20260630_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbapikey',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DataSourceUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('db', 'Database'), ('api', 'TMDB API'), ('api_fallback', 'TMDB API Fallback')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'unique_together': {('source', 'entity_type', 'entity_id', 'detail')},
            },
        ),
    ]
