# Generated by Django 6.0.6 on 2026-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_tmdbapikey_usage_count_datasourceusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Item',
                'verbose_name_plural': 'Provider Items',
                'ordering': ['name'],
            },
        ),
    ]
