# Generated by Django 6.0.6 on 2026-06-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_provideritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tmdb_db_enable_api_fallback',
            field=models.BooleanField(default=True, help_text='Allow TMDB API access and fallback when TMDB DB is selected'),
        ),
    ]
