# Generated by Django 6.0.6 on 2026-06-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_sitesettings_tmdb_db_enable_api_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tmdb_db_enabled',
            field=models.BooleanField(default=True, help_text='Enable TMDB Database access'),
        ),
    ]
