# Generated by Django 6.0.6 on 2026-06-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_sitesettings_tmdb_db_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMonthCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('month_name', models.CharField(max_length=20)),
                ('first_day', models.CharField(max_length=10)),
                ('last_day', models.CharField(max_length=10)),
                ('movies', models.JSONField(blank=True, default=list)),
                ('series', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
