# Generated by Django 6.0.6 on 2026-06-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_calendarmonthcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_bottom_text',
            field=models.CharField(default='Powered by TMDB data sources and your local media setup.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.CharField(default='Stream movies, TV shows, calendar updates, and watchlist content in one place.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_title',
            field=models.CharField(default='NETFLIX', max_length=100),
        ),
    ]
