# Generated by Django 6.0.6 on 2026-06-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_sitesettings_footer_bottom_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(default='Copyright © 2026 moviefake.com. All Rights Reserved', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_countries',
            field=models.TextField(blank=True, default='Australia\nCanada\nNetherlands\nUnited Kingdom\nUnited States'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_countries_title',
            field=models.CharField(default='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_disclaimer_text',
            field=models.CharField(default='Disclaimer: This site does not store any files on its server. All contents are provided by non-affiliated third parties.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_genres',
            field=models.TextField(blank=True, default='Action\nAnimation\nComedy\nDrama\nHorror'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_genres_title',
            field=models.CharField(default='Genres', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_links',
            field=models.TextField(blank=True, default="Movies\nTV-Series\nFAQ's\nDMCA"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_links_title',
            field=models.CharField(default='123movies', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo_tagline',
            field=models.CharField(default='Watch Your Favorite Movies Online', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo_text',
            field=models.CharField(default='123MOVIES', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_subscribe_button_text',
            field=models.CharField(default='Subscribe', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_subscribe_placeholder',
            field=models.CharField(default='Put your email', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_subscribe_text',
            field=models.CharField(default='Subscribe to the 123movies mailing list to receive updates on movies, tv-series and news of top movies.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_subscribe_title',
            field=models.CharField(default='Subscribe', max_length=100),
        ),
    ]
