# Generated by Django 6.0.6 on 2026-06-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sitesettings_footer_copyright_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
