# Generated by Django 6.0.6 on 2026-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_sitesettings_footer_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerconfiguration',
            name='custom_iframe_id_type',
            field=models.CharField(choices=[('tmdb', 'TMDB ID'), ('imdb', 'IMDb ID')], default='tmdb', help_text='Choose whether custom iframe placeholders should use the TMDB ID or IMDb ID', max_length=10),
        ),
        migrations.AddField(
            model_name='playerconfiguration',
            name='custom_movie_iframe_url',
            field=models.TextField(blank=True, help_text='Movie-specific custom iframe URL. Use placeholders: {content_id}, {tmdb_id}, {imdb_id}', null=True),
        ),
        migrations.AddField(
            model_name='playerconfiguration',
            name='custom_tv_iframe_url',
            field=models.TextField(blank=True, help_text='TV-specific custom iframe URL. Use placeholders: {content_id}, {tmdb_id}, {imdb_id}, {season}, {episode}', null=True),
        ),
        migrations.AlterField(
            model_name='playerconfiguration',
            name='custom_iframe_url',
            field=models.TextField(blank=True, help_text='Shared custom iframe URL. Use placeholders: {content_id}, {tmdb_id}, {imdb_id}, {season}, {episode}', null=True),
        ),
    ]
