# Generated by Django 6.0.6 on 2026-07-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_playerconfiguration_custom_iframe_id_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='url_format',
            field=models.CharField(choices=[('slug', 'Title (Slug)'), ('id', 'TMDB ID')], default='slug', help_text='URL format for movie/series detail pages', max_length=10),
        ),
    ]
