# Generated by Django 6.0.6 on 2026-07-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_sitesettings_url_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideritem',
            name='url',
            field=models.URLField(blank=True, help_text="Provider's homepage or official website", max_length=500, null=True),
        ),
    ]
