# Generated by Django 6.0.6 on 2026-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_provideritem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerconfiguration',
            name='custom_iframe_html',
            field=models.TextField(blank=True, help_text='Shared full custom iframe HTML. Use placeholders: {content_id}, {tmdb_id}, {imdb_id}, {season}, {episode}', null=True),
        ),
        migrations.AddField(
            model_name='playerconfiguration',
            name='custom_iframe_mode',
            field=models.CharField(choices=[('url', 'URL Mode - Enter URL, system creates iframe'), ('full', 'Full HTML Mode - Enter complete iframe HTML')], db_column='custom_type', default='url', help_text='Choose whether to use a simple URL (system creates iframe) or full HTML iframe code', max_length=10),
        ),
        migrations.AddField(
            model_name='playerconfiguration',
            name='custom_movie_iframe_html',
            field=models.TextField(blank=True, help_text='Movie-specific full custom iframe HTML. Use placeholders: {content_id}, {tmdb_id}, {imdb_id}', null=True),
        ),
        migrations.AddField(
            model_name='playerconfiguration',
            name='custom_tv_iframe_html',
            field=models.TextField(blank=True, help_text='TV-specific full custom iframe HTML. Use placeholders: {content_id}, {tmdb_id}, {imdb_id}, {season}, {episode}', null=True),
        ),
    ]
