# Generated by Django 6.0.6 on 2026-07-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_androidapp_apk_and_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidAppFailedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.CharField(choices=[('auth_missing', 'Missing Authorization Header'), ('auth_invalid_format', 'Invalid Authorization Format'), ('auth_invalid_creds', 'Invalid Credentials'), ('identity_invalid', 'Invalid Endpoint Identity'), ('app_inactive', 'App Not Active'), ('app_not_found', 'App Not Found')], max_length=50)),
                ('request_identity', models.CharField(blank=True, default='', max_length=500)),
                ('build_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('android_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failed_attempts', to='core.androidapp')),
            ],
            options={
                'verbose_name': 'Android App Failed Attempt',
                'verbose_name_plural': 'Android App Failed Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
