# Generated by Django 6.0.6 on 2026-07-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_androidappfailedattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapp',
            name='allowed_build_id',
            field=models.CharField(blank=True, default='', help_text='Allowed build identifier. Supports comma-separated lists and ranges (e.g., 1.0.0, 1.0.1 or 1-10)', max_length=255),
        ),
        migrations.AlterField(
            model_name='androidapp',
            name='allowed_endpoint',
            field=models.CharField(blank=True, default='', help_text='Allowed app/build identity. Supports comma-separated lists and ranges (e.g., #225, #226, #227 or #225-#250)', max_length=500),
        ),
        migrations.CreateModel(
            name='AndroidAppDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_id', models.CharField(db_index=True, max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('android_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.androidapp')),
            ],
            options={
                'verbose_name': 'Android App Device',
                'verbose_name_plural': 'Android App Devices',
                'ordering': ['-last_seen_at'],
                'unique_together': {('android_app', 'android_id')},
            },
        ),
        migrations.CreateModel(
            name='AndroidAppDeviceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('build_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('request_identity', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('android_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_visits', to='core.androidapp')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.androidappdevice')),
            ],
            options={
                'verbose_name': 'Android App Device Visit',
                'verbose_name_plural': 'Android App Device Visits',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='AndroidAppDailyUniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateField()),
                ('unique_visitor_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('android_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_unique_visitors', to='core.androidapp')),
            ],
            options={
                'verbose_name': 'Android App Daily Unique Visitor',
                'verbose_name_plural': 'Android App Daily Unique Visitors',
                'ordering': ['-access_date'],
                'unique_together': {('android_app', 'access_date')},
            },
        ),
    ]
