# Generated by Django 6.0.6 on 2026-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_androidapp_allowed_build_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androidappdevice',
            old_name='android_id',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='androidappdevice',
            unique_together={('android_app', 'user_id')},
        ),
        migrations.AddField(
            model_name='androidappdevice',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='androidappdevice',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='androidappdevicevisit',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='androidappdevicevisit',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
