# Generated by Django 6.0.6 on 2026-07-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rename_android_id_androidappdevice_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerconfiguration',
            name='auto_play',
        ),
        migrations.RemoveField(
            model_name='playerconfiguration',
            name='episode_selector',
        ),
        migrations.RemoveField(
            model_name='playerconfiguration',
            name='next_episode',
        ),
        migrations.AddField(
            model_name='playerconfiguration',
            name='use_for_android',
            field=models.BooleanField(default=False, help_text='Use this player configuration for Android app endpoints'),
        ),
    ]
