# Generated by Django 6.0.6 on 2026-07-16 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_playerconfiguration_auto_play_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_path', models.CharField(blank=True, default='', max_length=500)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Visitor',
                'verbose_name_plural': 'Website Visitors',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteVisitorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.websitevisitor')),
            ],
            options={
                'verbose_name': 'Website Visitor Visit',
                'verbose_name_plural': 'Website Visitor Visits',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='core_websit_visited_6bf86c_idx'), models.Index(fields=['path'], name='core_websit_path_11f1d0_idx')],
            },
        ),
    ]
