# Generated by Django 6.0.6 on 2026-07-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_websitevisitor_websitevisitorvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bot_ips',
            field=models.TextField(blank=True, help_text='Comma-separated list of IP addresses for our bot (e.g., 192.168.1.1,10.0.0.1)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bot_user_agents',
            field=models.TextField(blank=True, help_text='Comma-separated list of user-agent strings for our bot', null=True),
        ),
        migrations.AddField(
            model_name='websitevisitorvisit',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='Whether this visit is from our bot'),
        ),
    ]
