# Generated by Django 6.0.6 on 2026-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_sitesettings_bot_ips_sitesettings_bot_user_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ads_body_script',
            field=models.TextField(blank=True, help_text='HTML/JS code to add to the <body> tag (e.g., ad units)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ads_head_script',
            field=models.TextField(blank=True, help_text='HTML/JS code to add to the <head> tag (e.g., AdSense script)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='android_ads_config',
            field=models.TextField(blank=True, help_text='JSON configuration for Android ads', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_ads',
            field=models.BooleanField(default=False, help_text='Enable ads on the website'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_android_ads',
            field=models.BooleanField(default=False, help_text='Enable ads in the Android app'),
        ),
    ]
