# Generated by Django 6.0.6 on 2026-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_sitesettings_ads_body_script_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this ad (not shown publicly)', max_length=100)),
                ('network', models.CharField(choices=[('google_adsense', 'Google AdSense'), ('amazon_associates', 'Amazon Associates'), ('cj_affiliate', 'CJ Affiliate (Commission Junction)'), ('shareasale', 'ShareASale'), ('rakuten_advertising', 'Rakuten Advertising'), ('ebay_partner_network', 'eBay Partner Network'), ('clickbank', 'ClickBank'), ('maxbounty', 'MaxBounty'), ('mediavine', 'Mediavine'), ('adthrive', 'AdThrive'), ('other', 'Other / Custom')], default='other', help_text='Affiliate/Ad network for this ad', max_length=50)),
                ('position', models.CharField(choices=[('head', 'Head (All Pages)'), ('sidebar', 'Sidebar'), ('above_player', 'Above Video Player'), ('below_player', 'Below Video Player'), ('above_content', 'Above Main Content'), ('below_content', 'Below Main Content'), ('footer', 'Footer'), ('popup', 'Popup / Modal')], default='sidebar', help_text='Where this ad will appear on the site', max_length=50)),
                ('ad_code', models.TextField(blank=True, help_text='HTML/JS ad code from your network', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this ad')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers show first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
