# Generated by Django 6.0.6 on 2026-07-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='allowed_pages',
            field=models.TextField(blank=True, help_text='Comma separated list of page paths this ad should appear on (leave blank for all pages, e.g., /, /movies/, /series/)', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='clicks_required_before_show',
            field=models.IntegerField(default=0, help_text='Number of clicks user has to make on the site before this ad is shown (0 = no requirement)'),
        ),
        migrations.AddField(
            model_name='ad',
            name='max_impressions_per_day',
            field=models.IntegerField(default=0, help_text='Max number of times this ad can be shown per user per day (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='ad',
            name='pages_viewed_required_before_show',
            field=models.IntegerField(default=0, help_text='Number of pages user has to view before this ad is shown (0 = no requirement)'),
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_date', models.DateField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='core.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ad', 'view_date'], name='core_adimpr_ad_id_627555_idx'), models.Index(fields=['user', 'view_date'], name='core_adimpr_user_id_35079e_idx'), models.Index(fields=['ip_address', 'view_date'], name='core_adimpr_ip_addr_6dc46b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('activity_date', models.DateField(auto_now_add=True)),
                ('clicks_today', models.IntegerField(default=0)),
                ('pages_viewed_today', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'activity_date'], name='core_userac_user_id_a88216_idx'), models.Index(fields=['ip_address', 'activity_date'], name='core_userac_ip_addr_dc92cf_idx')],
                'unique_together': {('ip_address', 'activity_date'), ('user', 'activity_date')},
            },
        ),
    ]
