# Generated by Django 6.0.6 on 2026-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_ad_allowed_pages_ad_clicks_required_before_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='use_for_android',
            field=models.BooleanField(default=False, help_text='Use this ad in the Android app'),
        ),
    ]
