# Generated by Django 6.0.6 on 2026-07-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_ad_use_for_android'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adimpression',
            name='core_adimpr_ad_id_627555_idx',
        ),
        migrations.RemoveIndex(
            model_name='adimpression',
            name='core_adimpr_user_id_35079e_idx',
        ),
        migrations.RemoveIndex(
            model_name='adimpression',
            name='core_adimpr_ip_addr_6dc46b_idx',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ads_body_script',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ads_head_script',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='android_ads_config',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_ads',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_android_ads',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_sidebar_ads',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sidebar_ads_code',
        ),
        migrations.RemoveField(
            model_name='adimpression',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='adimpression',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='AdImpression',
        ),
    ]
