# Generated by Django 6.0.6
# Fixed: 0054 deleted Ad and AdImpression, this re-creates them with all current fields

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_adimpression_core_adimpr_ad_id_627555_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(default='custom_script', max_length=50)),
                ('position', models.CharField(default='sidebar', max_length=50)),
                ('script', models.TextField(blank=True, null=True)),
                ('affiliate_url', models.URLField(blank=True, null=True)),
                ('affiliate_image_url', models.URLField(blank=True, null=True)),
                ('affiliate_title', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_price', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('clicks_required', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('use_for_android', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('impression_date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='core.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ad', 'user', 'impression_date'), ('ad', 'ip_address', 'impression_date')},
            },
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ad', 'impression_date'], name='core_adimpr_ad_id_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['user', 'impression_date'], name='core_adimpr_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ip_address', 'impression_date'], name='core_adimpr_ip_addr_idx'),
        ),
    ]
