# Generated by Django 6.0.6 on 2026-07-22 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_adimpression_core_adimpr_ad_id_627555_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ad for internal use', max_length=255)),
                ('provider', models.CharField(choices=[('google_adsense', 'Google AdSense'), ('custom', 'Custom Script')], default='custom', max_length=50)),
                ('script', models.TextField(help_text='Ad script code')),
                ('clicks_required', models.IntegerField(default=0, help_text='Number of user clicks required before showing this ad')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ad is active and can be shown')),
                ('use_for_android', models.BooleanField(default=False, help_text='Include this ad in Android app responses')),
                ('order', models.IntegerField(default=0, help_text='Display order of the ad')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('impression_date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='core.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ad', 'impression_date'], name='core_adimpr_ad_id_b1de5e_idx'), models.Index(fields=['user', 'impression_date'], name='core_adimpr_user_id_77277b_idx'), models.Index(fields=['ip_address', 'impression_date'], name='core_adimpr_ip_addr_69fe2f_idx')],
                'unique_together': {('ad', 'ip_address', 'impression_date'), ('ad', 'user', 'impression_date')},
            },
        ),
    ]
