# Generated by Django 6.0.6 on 2026-07-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_ad_adimpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_client_id',
            field=models.CharField(blank=True, help_text='Google AdSense client ID (e.g., ca-pub-1234567890123456)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_verification_meta',
            field=models.CharField(blank=True, help_text='Google AdSense verification meta tag content (e.g., abcdef123456)', max_length=200, null=True),
        ),
    ]
