# Generated by Django 6.0.6
# No-op: fields already added by fixed 0055

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_sitesettings_adsense_client_id_and_more'),
    ]

    operations = []
