# Generated by Django 6.0.6 on 2026-07-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_sitesettings_adsense_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for custom banner ad image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL for custom banner ad', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='link_url',
            field=models.URLField(blank=True, help_text='Destination URL for custom banner ad', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='provider',
            field=models.CharField(choices=[('google_adsense', 'Google AdSense'), ('custom_script', 'Custom Script'), ('custom_image', 'Custom Image/Banner')], default='custom_script', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='script',
            field=models.TextField(blank=True, help_text='Ad script code (for Custom Script and Google AdSense)', null=True),
        ),
    ]
