# Generated by Django 6.0.6
# No-op: fields already added by fixed 0055

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_ad_alt_text_ad_image_url_ad_link_url_and_more'),
    ]

    operations = []
