# Generated by Django 6.0.6 on 2026-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_ad_alt_text_ad_image_url_ad_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='affiliate_image_url',
            field=models.URLField(blank=True, help_text='Amazon product image URL', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='affiliate_price',
            field=models.CharField(blank=True, help_text='Optional product price text', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='affiliate_title',
            field=models.CharField(blank=True, help_text='Product title shown in the affiliate card', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='Amazon Associates tracking/product URL', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='position',
            field=models.CharField(choices=[('head', 'Head (All Pages)'), ('sidebar', 'Sidebar'), ('above_player', 'Above Video Player'), ('below_player', 'Below Video Player'), ('above_content', 'Above Main Content'), ('below_content', 'Below Main Content'), ('footer', 'Footer'), ('popup', 'Popup / Modal')], default='sidebar', help_text='Where this ad will appear on the site', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers show first)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='provider',
            field=models.CharField(choices=[('google_adsense', 'Google AdSense'), ('amazon_affiliate', 'Amazon Affiliate'), ('custom_script', 'Custom Script'), ('custom_image', 'Custom Image/Banner')], default='custom_script', max_length=50),
        ),
    ]
