# Generated by Django 6.0.6 on 2026-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_ad_affiliate_image_url_ad_affiliate_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_click_timer_seconds',
            field=models.IntegerField(default=10, help_text='Seconds to wait (in background) before ad auto-click triggers on next user click. Set 0 to trigger immediately when eligible.'),
        ),
    ]
