# Generated by Django 6.0.6 on 2026-07-25 08:10
# Manual edit: use RenameField to preserve column data instead of drop+recreate.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_sitesettings_auto_click_timer_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='auto_click_timer_seconds',
            new_name='auto_click_every_clicks',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='auto_click_every_clicks',
            field=models.IntegerField(
                default=10,
                help_text='Number of user clicks (counted) between ad auto-open triggers. After this many clicks, the NEXT click triggers the ad tab to open. Set 1 to trigger on every eligible click.'
            ),
        ),
    ]
