# Generated by Django 6.0.6 on 2026-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_rename_timer_to_every_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ad_consent_message',
            field=models.TextField(default='We use third-party ads to keep this service free. By clicking "Accept", you agree to ad loading and cookies as described in our Privacy Policy.', help_text='GDPR/CCPA consent banner copy shown to users when require_ad_consent is enabled.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_clicks_required',
            field=models.IntegerField(default=0, help_text='Default click threshold required before ANY ad content loads on a page. Used as the effective Clicks Required for ads whose clicks_required is 0 (or not set). Set 0 to rely solely on per-Ad clicks_required.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_ad_load_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of automatic retries for failed ad network script/asset loads before the slot is marked failed.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_ad_consent',
            field=models.BooleanField(default=False, help_text='If checked, ad content will NEVER load until the user explicitly gives consent (GDPR/CCPA). A consent banner is shown until the user accepts or declines.'),
        ),
    ]
