# Generated by Django 6.0.6 on 2026-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_add_deferred_ad_loading_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='idm_visibility',
            field=models.CharField(choices=[('hide', 'Hide IDM (Disabled)'), ('logged_in', 'Logged-In Users Only'), ('admin_only', 'Admin / Staff Users Only'), ('all_users', 'All Users (Include Guests)')], default='all_users', help_text="Who can see and use the IDM Auto-Extract button and UI. Use 'Admin / Staff Users Only' to restrict this feature to site administrators, or 'Hide IDM' to disable it entirely.", max_length=20),
        ),
    ]
