# Generated by Django 6.0.6 on 2026-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_idm_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_tile_click_gating',
            field=models.BooleanField(default=True, help_text='If enabled, the first click on a movie/series card opens an ad (new tab), the second click on the same card navigates to the detail page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tile_ad_every_n',
            field=models.IntegerField(default=10, help_text='Insert an in-grid ad tile every N movie/series cards. Set 0 to disable tile ads entirely. Example: 10 = one ad tile after every 10 cards.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.CharField(choices=[('head', 'Head (All Pages)'), ('sidebar', 'Sidebar'), ('above_player', 'Above Video Player'), ('below_player', 'Below Video Player'), ('above_content', 'Above Main Content'), ('below_content', 'Below Main Content'), ('footer', 'Footer'), ('popup', 'Popup / Modal'), ('tile', 'Tile / Card (In-Grid)')], default='sidebar', help_text='Where this ad will appear on the site', max_length=50),
        ),
    ]
