# Generated by Django 6.0.6 on 2026-07-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_sitesettings_enable_tile_click_gating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAffiliateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_url', models.URLField(help_text='Full Amazon affiliate link including your tracking tag (e.g. https://www.amazon.com/dp/B08XYZ/?tag=yourname-20)', max_length=1000)),
                ('title', models.CharField(blank=True, help_text='Product name shown on the ad tile.', max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Product cover image URL (Amazon CDN or your own).', max_length=1000, null=True)),
                ('price', models.CharField(blank=True, help_text="Optional price text, e.g. $29.99 or 'From $9.99'.", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to exclude this product from rotation without deleting it.')),
                ('order', models.IntegerField(default=0, help_text='Display order / sequence position (lower numbers come first when using Sequence mode).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amazon Affiliate Product',
                'verbose_name_plural': 'Amazon Affiliate Products',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tile_ad_source',
            field=models.CharField(choices=[('ads_table', 'Ad records with position=Tile (from Ads page)'), ('amazon_random', 'Amazon Affiliate Product List (Random)'), ('amazon_sequence', 'Amazon Affiliate Product List (In Sequence)')], default='ads_table', help_text='Where the in-grid ad tile content comes from — either individual Tile-position Ad records, or the bulk Amazon Affiliate Product list.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tile_gating_source',
            field=models.CharField(choices=[('autoclick_urls', 'All active ad URLs (autoclick pool)'), ('amazon_random', 'Amazon Affiliate Product List (Random)'), ('amazon_sequence', 'Amazon Affiliate Product List (In Sequence)')], default='autoclick_urls', help_text='Where the first-click-gating ad URL comes from — the global autoclick ad pool, or the Amazon Affiliate Product list.', max_length=20),
        ),
    ]
