# Generated by Django 6.0.6 on 2026-08-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_amazonaffiliateproduct_sitesettings_tile_ad_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 3166-1 country code, e.g. US, IN, GB', max_length=2, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Watch Region',
                'verbose_name_plural': 'Watch Regions',
                'ordering': ['display_order', 'name', 'code'],
            },
        ),
        migrations.AlterModelOptions(
            name='provideritem',
            options={'ordering': ['display_priority', 'name'], 'verbose_name': 'Provider Item', 'verbose_name_plural': 'Provider Items'},
        ),
        migrations.AddField(
            model_name='provideritem',
            name='display_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provideritem',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideritem',
            name='logo_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='provideritem',
            name='supports_movies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provideritem',
            name='supports_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provideritem',
            name='tmdb_provider_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProviderRegionAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', 'Movies'), ('tv', 'TV Series')], max_length=10)),
                ('display_priority', models.IntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_availability', to='core.provideritem')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_availability', to='core.watchregion')),
            ],
            options={
                'verbose_name': 'Provider Region Availability',
                'verbose_name_plural': 'Provider Region Availability',
                'ordering': ['region__code', 'media_type', 'display_priority', 'provider__name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'region', 'media_type'), name='unique_provider_region_media')],
            },
        ),
    ]
