# Generated by Django 6.0.6 on 2026-08-21 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_watchregion_alter_provideritem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_color',
            field=models.CharField(default='#00c896', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='newmovies', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_disclaimer_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_links_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_logo_tagline',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_logo_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_subscribe_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_style',
            field=models.CharField(choices=[('cinevault', 'CineVault (Cinematic Dark)'), ('netflix', 'Netflix (Dark Red)'), ('amazon', 'Amazon Prime (Dark Blue)'), ('hbo', 'HBO Max (Dark Purple)'), ('disney', 'Disney+ (Dark Blue/Teal)'), ('spotify', 'Spotify (Dark Green)')], default='cinevault', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
