# Generated by Django 6.0.6 on 2026-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_emaildelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='data_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days to retain analytics logs. Older data is automatically deleted.'),
        ),
    ]
