# Generated by Django 6.0.6 on 2026-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_add_data_retention_days'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adimpression',
            new_name='core_adimpr_ad_id_b1de5e_idx',
            old_name='core_adimpr_ad_id_idx',
        ),
        migrations.RenameIndex(
            model_name='adimpression',
            new_name='core_adimpr_user_id_77277b_idx',
            old_name='core_adimpr_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='adimpression',
            new_name='core_adimpr_ip_addr_69fe2f_idx',
            old_name='core_adimpr_ip_addr_idx',
        ),
        migrations.AlterField(
            model_name='ad',
            name='affiliate_image_url',
            field=models.URLField(blank=True, help_text='Amazon product image URL', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='affiliate_price',
            field=models.CharField(blank=True, help_text='Optional product price text', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='affiliate_title',
            field=models.CharField(blank=True, help_text='Product title shown in the affiliate card', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='Amazon Associates tracking/product URL', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for custom banner ad image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='clicks_required',
            field=models.IntegerField(default=0, help_text='Number of user clicks required before showing this ad'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL for custom banner ad', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this ad is active and can be shown'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link_url',
            field=models.URLField(blank=True, help_text='Destination URL for custom banner ad', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(help_text='Name of the ad for internal use', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers show first)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='provider',
            field=models.CharField(choices=[('google_adsense', 'Google AdSense'), ('amazon_affiliate', 'Amazon Affiliate'), ('custom_script', 'Custom Script'), ('custom_image', 'Custom Image/Banner')], default='custom_script', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='script',
            field=models.TextField(blank=True, help_text='Ad script code (for Custom Script and Google AdSense)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='use_for_android',
            field=models.BooleanField(default=False, help_text='Include this ad in Android app responses'),
        ),
    ]
