# Generated by Django 6.0.6 on 2026-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_rename_core_adimpr_ad_id_idx_core_adimpr_ad_id_b1de5e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('photo_url', models.URLField(blank=True, default='')),
                ('google_id', models.CharField(blank=True, default='', max_length=100)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('build_number', models.IntegerField(default=0)),
                ('device_id', models.CharField(blank=True, default='', max_length=100)),
                ('device_model', models.CharField(blank=True, default='', max_length=100)),
                ('os_version', models.CharField(blank=True, default='', max_length=50)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('plan', models.CharField(blank=True, default='', max_length=100)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_synced_at'],
            },
        ),
    ]
