# Generated by Django 6.0.6 on 2026-08-24 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_synceduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('episode_title', models.CharField(blank=True, default='', max_length=255)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_played_at'],
                'indexes': [models.Index(fields=['user', 'last_played_at'], name='core_playhi_user_id_3a32b9_idx')],
                'unique_together': {('user', 'tmdb_id', 'media_type', 'season_number', 'episode_number')},
            },
        ),
    ]
