# Generated by Django 6.0.6 on 2026-08-25 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCloudData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playback_progress', models.JSONField(blank=True, default=dict)),
                ('seen_keys', models.JSONField(blank=True, default=list)),
                ('watch_history', models.JSONField(blank=True, default=list)),
                ('favorites', models.JSONField(blank=True, default=list)),
                ('watchlist_ids', models.JSONField(blank=True, default=list)),
                ('user_ratings', models.JSONField(blank=True, default=dict)),
                ('data_version', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Cloud Data',
                'verbose_name_plural': 'User Cloud Data',
            },
        ),
    ]
