# Generated by Django 6.0.6 on 2026-08-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_userclouddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclouddata',
            name='app_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userclouddata',
            name='downloads',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userclouddata',
            name='playlists',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
