# Generated by Django 6.0.6 on 2026-08-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_userclouddata_app_settings_userclouddata_downloads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.EmailField(blank=True, default='', max_length=254)),
                ('smtp_password', models.CharField(max_length=200)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('notification', 'Notifications'), ('newsletter', 'Newsletter'), ('marketing', 'Marketing'), ('transactional', 'Transactional')], default='notification', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default email for its purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email Addresses',
                'ordering': ['-is_default', 'purpose', 'email'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('notification', 'Notifications'), ('newsletter', 'Newsletter'), ('marketing', 'Marketing'), ('transactional', 'Transactional')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use {variable} placeholders: {name}, {email}, {link}, {code}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['purpose', 'name'],
            },
        ),
    ]
