# Generated by Django 6.0.6 on 2026-08-26 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(help_text='Recipient email address', max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('purpose', models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('notification', 'Notifications'), ('newsletter', 'Newsletter'), ('marketing', 'Marketing'), ('transactional', 'Transactional')], default='notification', max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('test_mail', 'Test Mail'), ('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('notification', 'Notification'), ('api', 'API')], default='test_mail', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, help_text='SMTP address used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailaddress')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Admin who triggered it', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Send Log',
                'verbose_name_plural': 'Email Send Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
