# Generated by Django 6.0.6 on 2026-08-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_emailsendlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBConnectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this connection', max_length=100)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL / MariaDB'), ('oracle', 'Oracle'), ('postgresql', 'PostgreSQL'), ('mssql', 'MS SQL Server'), ('sqlite', 'SQLite')], default='mysql', max_length=20)),
                ('host', models.CharField(default='127.0.0.1', help_text='IP address or hostname (use 127.0.0.1 for VM-local)', max_length=255)),
                ('port', models.IntegerField(default=3306, help_text='Database port')),
                ('database_name', models.CharField(default='', help_text='Database name', max_length=255)),
                ('username', models.CharField(default='', help_text='Database username', max_length=255)),
                ('password', models.CharField(default='', help_text='Database password', max_length=255)),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Extra connection params as JSON, e.g. {"charset": "utf8mb4"}')),
                ('is_active', models.BooleanField(default=True, help_text='Only one connection can be active at a time')),
                ('is_default', models.BooleanField(default=False, help_text='Use as the default external DB connection')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('untested', 'Untested')], default='untested', max_length=20)),
                ('last_test_message', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='', help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DB Connection Config',
                'verbose_name_plural': 'DB Connection Configs',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
    ]
