# Generated by Django 6.0.6 on 2026-08-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_add_dbconnectionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBRoutingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_external_db', models.BooleanField(default=False, help_text='Route user data (users, watchlist, play history, etc.) to the external database configured in DB Connections')),
                ('auto_migrate_on_switch', models.BooleanField(default=True, help_text='Automatically migrate existing user data when switching databases')),
                ('last_migrated_at', models.DateTimeField(blank=True, null=True)),
                ('last_migration_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_migration_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DB Routing Config',
                'verbose_name_plural': 'DB Routing Config',
            },
        ),
    ]
