# Generated by Django 6.0.6 on 2026-08-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_add_dbroutingconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('page_title', models.CharField(blank=True, default='', max_length=255)),
                ('platform', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android App'), ('ios', 'iOS App'), ('unknown', 'Unknown')], default='web', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Seconds spent on this page')),
                ('scroll_depth', models.FloatField(default=0, help_text='Max scroll depth percentage (0-100)')),
                ('is_active', models.BooleanField(default=True, help_text='Currently viewing')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='core_userpa_user_id_51a6e1_idx'), models.Index(fields=['path', 'viewed_at'], name='core_userpa_path_408090_idx'), models.Index(fields=['platform', 'viewed_at'], name='core_userpa_platfor_761187_idx')],
            },
        ),
    ]
