# Generated by Django 6.0.6 on 2026-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_userpageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='player_ui_style',
            field=models.CharField(choices=[('default', 'Classic Player'), ('netflix', 'Netflix-Style Player')], default='default', help_text='Player UI style for video playback', max_length=20),
        ),
    ]
