# Generated by Django 6.0.6 on 2026-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_sitesettings_player_ui_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidappdevicevisit',
            name='full_request',
            field=models.TextField(blank=True, default='', help_text='Full request details (headers, params, etc.) for debugging'),
        ),
    ]
