# Generated by Django 6.0.6 on 2026-08-29 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_add_full_request_to_device_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warn', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], default='info', max_length=20)),
                ('tag', models.CharField(blank=True, default='', help_text='Log tag / category', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.TextField(blank=True, default='', help_text='JSON payload for extra context')),
                ('build_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('device_model', models.CharField(blank=True, default='', max_length=255)),
                ('os_version', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('android_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_logs', to='core.androidapp')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_logs', to='core.androidappdevice')),
            ],
            options={
                'verbose_name': 'Android App Log',
                'verbose_name_plural': 'Android App Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['android_app', '-timestamp'], name='core_androi_android_8c385a_idx'), models.Index(fields=['level'], name='core_androi_level_705521_idx')],
            },
        ),
    ]
