# Generated by Django 6.0.8 on 2026-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_add_password_reset_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="otp",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
    ]
