# Generated by Django 6.0.8 on 2026-09-04 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_emailverification_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playhistory",
            name="last_played_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
