# Generated by Django 6.0.8 on 2026-09-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_device_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="CinePlayerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Enable CinePlayer as a server option"
                    ),
                ),
                (
                    "gateway_url",
                    models.URLField(
                        default="http://127.0.0.1:8787",
                        help_text="Cinevault gateway URL (port 8787)",
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        default="209173008",
                        help_text="Referral invite code for new device registrations",
                        max_length=50,
                    ),
                ),
                (
                    "share_url",
                    models.URLField(
                        default="https://c53l.1zor.com/sharex/moviein/index_fb3000.html",
                        help_text="Share/invite landing URL (fired on first device visit)",
                    ),
                ),
                (
                    "referrer_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of referrer URLs for the share link (cycle through these)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin note describing this CinePlayer instance",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="CinePlayer",
                        help_text="Title shown on the CinePlayer page",
                        max_length=200,
                    ),
                ),
                (
                    "site_subtitle",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subtitle/tagline",
                        max_length=300,
                    ),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Default poster for unresolved titles",
                    ),
                ),
                (
                    "auto_play",
                    models.BooleanField(
                        default=True, help_text="Auto-play on page load"
                    ),
                ),
                (
                    "show_next_episode",
                    models.BooleanField(
                        default=True, help_text="Show Next Episode button for series"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CinePlayer Configuration",
                "verbose_name_plural": "CinePlayer Configuration",
            },
        ),
    ]
