# Generated by Django 6.0.8 on 2026-10-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_cineplayer_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="google_analytics_id",
            field=models.CharField(
                blank=True,
                help_text="Google Analytics 4 measurement ID (e.g., G-XXXXXXXXXX). Leave blank to disable analytics.",
                max_length=50,
                null=True,
            ),
        ),
    ]
