# Generated by Django 6.0.8 on 2026-10-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_sitesettings_google_analytics_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("api", "API"), ("server", "Server")],
                        default="server",
                        max_length=10,
                    ),
                ),
                ("status_code", models.PositiveIntegerField(default=500)),
                ("view_name", models.CharField(blank=True, default="", max_length=120)),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                ("path", models.CharField(blank=True, default="", max_length=500)),
                ("query", models.CharField(blank=True, default="", max_length=500)),
                ("client_ip", models.CharField(blank=True, default="", max_length=64)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "error_type",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("traceback", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="errorlog_created_idx"),
                    models.Index(
                        fields=["kind", "-created_at"], name="errorlog_kind_idx"
                    ),
                    models.Index(
                        fields=["status_code", "-created_at"],
                        name="errorlog_status_idx",
                    ),
                ],
            },
        ),
    ]
