# Generated by Django 6.0.8 on 2026-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_errorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="adsterra_ad_url",
            field=models.URLField(
                blank=True,
                help_text="Adsterra direct link / smartlink URL. Opened in a new tab once the click threshold is reached, and shown as a sponsor block on movie and series pages.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="adsterra_click_count",
            field=models.IntegerField(
                default=0,
                help_text="Total number of times the Adsterra ad page has been opened (counted automatically).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="adsterra_clicks_required",
            field=models.IntegerField(
                default=5,
                help_text="Number of user clicks after which the Adsterra ad page opens in the browser. Set 0 to disable auto-open.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="adsterra_show_banner",
            field=models.BooleanField(
                default=True,
                help_text="Show the Adsterra sponsor block on movies and series pages.",
            ),
        ),
    ]
