# Generated by Django 6.0.8 on 2026-10-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_sitesettings_adsterra_ad_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsterraLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Adsterra direct link / smartlink URL.",
                        max_length=1000,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable this link. Only enabled links open and show on movie/series pages.",
                    ),
                ),
                (
                    "click_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this link has been opened (counted automatically).",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display / rotation order (lower numbers come first).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Adsterra Link",
                "verbose_name_plural": "Adsterra Links",
                "ordering": ["order", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="adsterra_ad_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="adsterra_click_count",
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="adsterra_clicks_required",
            field=models.IntegerField(
                default=5,
                help_text="Number of user clicks after which the next enabled Adsterra link opens in the browser. Set 0 to disable auto-open.",
            ),
        ),
    ]
