# Generated by Django 6.0.8 on 2026-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_adsterralink_remove_sitesettings_adsterra_ad_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsterralink",
            name="ad_type",
            field=models.CharField(
                blank=True,
                help_text="Adsterra ad format, e.g. Popunder, Smartlink, Social Bar, Native Banner, Banner 320x50.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adsterralink",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Label for this Adsterra unit, e.g. Popunder_1.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adsterralink",
            name="unit_id",
            field=models.CharField(
                blank=True,
                help_text="Adsterra ad unit / placement ID, e.g. 30866764.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adsterralink",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable this link. Only enabled links with a URL open and show on movie/series pages.",
            ),
        ),
        migrations.AlterField(
            model_name="adsterralink",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Adsterra direct link / smartlink URL for this unit.",
                max_length=1000,
                null=True,
            ),
        ),
    ]
