# Generated by Django 6.0.8 on 2026-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_seed_adsterra_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsterralink",
            name="code",
            field=models.TextField(
                blank=True,
                help_text="Adsterra JS / HTML ad code. Used for script-type units (Popunder, Social Bar, Native Banner, Banner 320x50).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adsterralink",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable this unit. Only enabled units with a URL open, and only enabled units with code render on movie/series pages.",
            ),
        ),
        migrations.AlterField(
            model_name="adsterralink",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Adsterra direct link / smartlink URL. Used for link-type units (e.g. Smartlink).",
                max_length=1000,
                null=True,
            ),
        ),
    ]
