# Generated by Django 6.0.8 on 2026-10-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_adsterralink_code_alter_adsterralink_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("api", "API / Ajax"),
                            ("admin", "Admin"),
                        ],
                        default="page",
                        max_length=10,
                    ),
                ),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                ("path", models.CharField(blank=True, default="", max_length=500)),
                ("query", models.CharField(blank=True, default="", max_length=500)),
                ("status_code", models.PositiveIntegerField(default=200)),
                ("client_ip", models.CharField(blank=True, default="", max_length=64)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("referer", models.CharField(blank=True, default="", max_length=500)),
                ("view_name", models.CharField(blank=True, default="", max_length=120)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="reqlog_created_idx"),
                    models.Index(
                        fields=["category", "-created_at"], name="reqlog_cat_idx"
                    ),
                    models.Index(
                        fields=["method", "-created_at"], name="reqlog_method_idx"
                    ),
                    models.Index(
                        fields=["status_code", "-created_at"], name="reqlog_status_idx"
                    ),
                ],
            },
        ),
    ]
