# Generated by Django 6.0.8 on 2026-10-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_requestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="request_body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="response_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
