# Generated by Django 6.0.8 on 2026-10-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_requestlog_request_body_requestlog_response_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="time_on_page_ms",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
