# Generated by Django 6.0.8 on 2026-10-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_requestlog_click_count_requestlog_time_on_page_ms"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLogPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("query", models.CharField(blank=True, default="", max_length=1000)),
                ("is_system", models.BooleanField(default=False)),
                ("owner", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_system", "name"],
            },
        ),
    ]
