# Generated by Django 6.0.8 on 2026-10-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_seed_request_log_presets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApkDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_slug", models.CharField(blank=True, default="", max_length=255)),
                ("file_name", models.CharField(blank=True, default="", max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("referer", models.CharField(blank=True, default="", max_length=500)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("opened_app", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "device_model",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("os_version", models.CharField(blank=True, default="", max_length=50)),
                (
                    "build_identifier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "android_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apk_downloads",
                        to="core.androidapp",
                    ),
                ),
            ],
            options={
                "verbose_name": "APK Download",
                "verbose_name_plural": "APK Downloads",
                "ordering": ["-downloaded_at"],
                "indexes": [
                    models.Index(fields=["-downloaded_at"], name="apkdl_created_idx"),
                    models.Index(fields=["ip_address"], name="apkdl_ip_idx"),
                    models.Index(
                        fields=["android_app", "-downloaded_at"], name="apkdl_app_idx"
                    ),
                ],
            },
        ),
    ]
