# Generated by Django 6.0.8 on 2026-10-07 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_apkdownload"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=64, unique=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                (
                    "blocked_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("blocked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("unblocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unblocked_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
            ],
            options={
                "verbose_name": "Blocked IP",
                "verbose_name_plural": "Blocked IPs",
                "ordering": ["-blocked_at"],
            },
        ),
    ]
