# Generated by Django 6.0.8 on 2026-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_blockedip"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockedip",
            name="is_permanent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blockedip",
            name="lifted_by_signup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blockedip",
            name="offense_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
