# Generated by Django 6.0.8 on 2026-10-07 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_blockedip_is_permanent_blockedip_lifted_by_signup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_name", models.CharField(default="User-Agent", max_length=100)),
                ("value", models.CharField(max_length=400)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                (
                    "blocked_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("blocked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("unblocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unblocked_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("robots_disallow", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Blocked header",
                "verbose_name_plural": "Blocked headers",
                "ordering": ["-blocked_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("header_name", "value"), name="unique_blocked_header"
                    )
                ],
            },
        ),
    ]
