# Generated by Django 6.0.8 on 2026-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_blockedheader"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="enable_adsterra_links",
            field=models.BooleanField(
                default=True,
                help_text="Master switch for the Adsterra direct-link units: when unchecked, URL units never open automatically, even if the click threshold is reached.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_autoclick_ads",
            field=models.BooleanField(
                default=True,
                help_text="Master switch for click-count auto-click ads: when unchecked, no ad is opened from page clicks, whatever auto_click_every_clicks is set to.",
            ),
        ),
    ]
