from django.urls import path
from django.views.generic import TemplateView
from . import views
from . import local_player
from . import streaming_views

handler404 = 'core.views.page_not_found_view'
handler403 = 'core.views.permission_denied_view'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('upcoming/', views.upcoming, name='upcoming'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/edit-settings/', views.edit_settings, name='edit_settings'),
    path('admin-dashboard/settings/branding/', views.branding_settings, name='branding_settings'),
    path('admin-dashboard/settings/display/', views.display_settings, name='display_settings'),
    path('admin-dashboard/settings/data-source/', views.data_source_settings, name='data_source_settings'),
    path('admin-dashboard/settings/footer/', views.footer_settings, name='footer_settings'),
    path('admin-dashboard/settings/data-source-config/', views.data_source_config, name='data_source_config'),
    path('admin-dashboard/settings/data-source-usage-stats/', views.data_source_usage_stats, name='data_source_usage_stats'),
    path('admin-dashboard/settings/tmdb-db/', views.tmdb_db_settings, name='tmdb_db_settings'),
    path('admin-dashboard/settings/player/', views.player_settings, name='player_settings'),
    path('admin-dashboard/settings/url-blocking/', views.url_blocking_settings, name='url_blocking_settings'),
    path('admin-dashboard/settings/email/', views.email_settings, name='email_settings'),
    path('admin-dashboard/content-rows/', views.content_row_list, name='content_row_list'),
    path('admin-dashboard/content-rows/create/', views.content_row_create, name='content_row_create'),
    path('admin-dashboard/content-rows/<int:row_id>/edit/', views.content_row_edit, name='content_row_edit'),
    path('admin-dashboard/content-rows/<int:row_id>/delete/', views.content_row_delete, name='content_row_delete'),
    path('admin-dashboard/players/', views.player_list, name='player_list'),
    path('admin-dashboard/players/create/', views.player_create, name='player_create'),
    path('admin-dashboard/players/<int:player_id>/edit/', views.player_edit, name='player_edit'),
    path('admin-dashboard/players/<int:player_id>/delete/', views.player_delete, name='player_delete'),
    path('admin-dashboard/players/<int:player_id>/toggle/', views.toggle_player, name='toggle_player'),
    path('admin-dashboard/ads/', views.ad_list, name='ad_list'),
    path('admin-dashboard/ads/create/', views.ad_create, name='ad_create'),
    path('admin-dashboard/ads/<int:ad_id>/edit/', views.ad_edit, name='ad_edit'),
    path('admin-dashboard/ads/<int:ad_id>/delete/', views.ad_delete, name='ad_delete'),
    path('admin-dashboard/ads/<int:ad_id>/toggle/', views.ad_toggle, name='ad_toggle'),
    path('ajax/track-click/', views.track_user_click, name='track_user_click'),
    path('ajax/autoclick-ads/', views.ajax_get_autoclick_ads, name='ajax_get_autoclick_ads'),
    path('ajax/click-status/', views.ajax_click_status, name='ajax_click_status'),
    path('ajax/record-ad-event/', views.ajax_record_ad_event, name='ajax_record_ad_event'),
    path('ajax/ad-consent/', views.ajax_give_ad_consent, name='ajax_give_ad_consent'),
    path('admin-dashboard/navbar-items/', views.navbar_item_list, name='navbar_item_list'),
    path('admin-dashboard/navbar-items/create/', views.navbar_item_create, name='navbar_item_create'),
    path('admin-dashboard/navbar-items/<int:item_id>/edit/', views.navbar_item_edit, name='navbar_item_edit'),
    path('admin-dashboard/navbar-items/<int:item_id>/delete/', views.navbar_item_delete, name='navbar_item_delete'),
    path('admin-dashboard/providers/', views.provider_item_list, name='provider_item_list'),
    path('admin-dashboard/providers/create/', views.provider_item_create, name='provider_item_create'),
    path('admin-dashboard/providers/<int:provider_id>/edit/', views.provider_item_edit, name='provider_item_edit'),
    path('admin-dashboard/providers/<int:provider_id>/delete/', views.provider_item_delete, name='provider_item_delete'),
    path('admin-dashboard/providers/<int:provider_id>/toggle/', views.provider_item_toggle, name='provider_item_toggle'),
    path('admin-dashboard/providers/sync/', views.provider_item_sync, name='provider_item_sync'),
    path('admin-dashboard/watch-regions/', views.watch_region_list, name='watch_region_list'),
    path('admin-dashboard/watch-regions/create/', views.watch_region_create, name='watch_region_create'),
    path('admin-dashboard/watch-regions/<int:region_id>/edit/', views.watch_region_edit, name='watch_region_edit'),
    path('admin-dashboard/watch-regions/<int:region_id>/delete/', views.watch_region_delete, name='watch_region_delete'),
    path('admin-dashboard/watch-regions/<int:region_id>/toggle/', views.watch_region_toggle, name='watch_region_toggle'),
    path('admin-dashboard/android-apps/', views.android_app_list, name='android_app_list'),
    path('admin-dashboard/android-apps/create/', views.android_app_create, name='android_app_create'),
    path('admin-dashboard/android-apps/<int:app_id>/toggle/', views.toggle_android_app, name='toggle_android_app'),
    path('admin-dashboard/android-apps/<int:app_id>/edit/', views.android_app_edit, name='android_app_edit'),
    path('admin-dashboard/android-apps/<int:app_id>/delete/', views.android_app_delete, name='android_app_delete'),
    path('admin-dashboard/android-apps/analytics/', views.android_app_dashboard, name='android_app_dashboard'),
    path('admin-dashboard/android-apps/<int:app_id>/analytics/', views.android_app_dashboard, name='android_app_dashboard_detail'),
    path('admin-dashboard/android-apps/<int:app_id>/failed-attempts/', views.android_app_failed_attempts, name='android_app_failed_attempts'),
    path('admin-dashboard/android-apps/user-sync-reference/', views.android_user_sync_reference, name='android_user_sync_reference'),
    # Android API endpoints — with and without trailing slash for app compat
    path('api/user/sync/', views.api_user_sync, name='api_user_sync'),
    path('api/user/sync', views.api_user_sync),
    path('api/user/register/', views.api_user_register, name='api_user_register'),
    path('api/user/register', views.api_user_register),
    path('api/user/login/', views.api_user_login, name='api_user_login'),
    path('api/user/login', views.api_user_login),
    path('api/user/refresh/', views.api_user_refresh_token, name='api_user_refresh_token'),
    path('api/user/refresh', views.api_user_refresh_token),
    path('api/user/forgot-password/', views.api_user_forgot_password, name='api_user_forgot_password'),
    path('api/user/forgot-password', views.api_user_forgot_password),
    path('api/user/profile/', views.api_user_profile, name='api_user_profile'),
    path('api/user/profile', views.api_user_profile),
    path('admin-dashboard/synced-users/', views.synced_users_list, name='synced_users_list'),
    path('admin-dashboard/synced-users/<int:user_id>/', views.synced_user_detail, name='synced_user_detail'),
    path('admin-dashboard/synced-users/<int:user_id>/edit/', views.synced_user_edit, name='synced_user_edit'),
    path('admin-dashboard/synced-users/<int:user_id>/delete/', views.synced_user_delete, name='synced_user_delete'),
    path('admin-dashboard/user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('admin-dashboard/android-apps/<int:app_id>/analytics/json/', views.ajax_android_app_dashboard, name='ajax_android_app_dashboard'),
    path('admin-dashboard/web-management/', views.web_management_dashboard, name='web_management_dashboard'),
    path('admin-dashboard/web-management/data/', views.ajax_web_management_dashboard, name='ajax_web_management_dashboard'),
    path('admin-dashboard/system-resources/', views.system_resource_dashboard, name='system_resource_dashboard'),
    path('admin-dashboard/system-resources/data/', views.ajax_system_resource_dashboard, name='ajax_system_resource_dashboard'),
    path('api/android-apps/<slug:app_slug>/', views.android_app_endpoint, name='android_app_endpoint'),
    path('movies/', views.movie_list, name='movie_list'),
    path('movies/id/<int:movie_id>/', views.movie_detail_by_id, name='movie_detail_by_id'),
    path('movies/<slug:movie_slug>/', views.movie_detail, name='movie_detail'),
    path('series/', views.series_list, name='series_list'),
    path('series/id/<int:series_id>/', views.series_detail_by_id, name='series_detail_by_id'),
    path('series/id/<int:series_id>/season/<int:season_number>/episodes/', views.series_season_episodes, name='series_season_episodes'),
    path('series/<slug:series_slug>/', views.series_detail, name='series_detail'),
    path('search/', views.search, name='search'),
    path('live-tv/', views.live_tv, name='live_tv'),
    path('row/<int:row_id>/load-more/', views.load_more_row_content, name='load_more_row_content'),
    path('ajax/home-data/', views.home_initial_data, name='home_initial_data'),
    path('ajax/home-row/', views.home_row_ajax, name='home_row_ajax'),
    path('ajax/home-top/', views.home_top_ajax, name='home_top_ajax'),
    path('ajax/login/', views.ajax_login, name='ajax_login'),
    path('ajax/register/', views.ajax_register, name='ajax_register'),
    path('ajax/verify-email/', views.verify_email, name='verify_email'),
    path('ajax/logout/', views.ajax_logout, name='ajax_logout'),
    path('ajax/forgot-password/', views.ajax_forgot_password, name='ajax_forgot_password'),
    path('reset-password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path('ajax/toggle-watchlist/', views.ajax_toggle_watchlist, name='ajax_toggle_watchlist'),
    path('ajax/check-watchlist/', views.ajax_check_watchlist, name='ajax_check_watchlist'),
    path('ajax/record-play/', views.ajax_record_play_progress, name='ajax_record_play_progress'),
    path('ajax/play-progress/', views.ajax_play_progress, name='ajax_play_progress'),
    path('ajax/resume-position/', views.ajax_resume_position, name='ajax_resume_position'),
    path('play-history/', views.user_play_history, name='user_play_history'),
    path('ajax/fetch-wikipedia/', views.fetch_wikipedia, name='fetch_wikipedia'),
    path('watchlist/', views.watchlist, name='watchlist'),
    path('ajax/calendar/movies/', views.calendar_movies, name='calendar_movies'),
    path('ajax/calendar/series/', views.calendar_series, name='calendar_series'),
    path('ajax/extract-video/', views.extract_video_url, name='extract_video_url'),
    path('ajax/download-proxy/', views.download_proxy, name='download_proxy'),
    path('ajax/proxy-embed/', views.proxy_embed, name='proxy_embed'),
    path('ajax/fetch-sources/', views.fetch_embed_sources, name='fetch_embed_sources'),
    path('ajax/test-db-connection/', views.test_db_connection, name='test_db_connection'),
    path('ajax/add-api-key/', views.add_api_key, name='add_api_key'),
    path('ajax/update-api-key/<int:key_id>/', views.update_api_key, name='update_api_key'),
    path('ajax/delete-api-key/<int:key_id>/', views.delete_api_key, name='delete_api_key'),
    path('ajax/toggle-api-key/<int:key_id>/', views.toggle_api_key, name='toggle_api_key'),
    path('ajax/toggle-hide-live-tv/', views.toggle_hide_live_tv, name='toggle_hide_live_tv'),
    path('ajax/toggle-footer/', views.toggle_footer, name='toggle_footer'),
    path('ajax/set-data-source/', views.set_data_source, name='set_data_source'),
    path('ajax/test-tmdb-api/', views.test_tmdb_api, name='test_tmdb_api'),
    path('ajax/save-db-config/', views.save_db_config, name='save_db_config'),
    path('ajax/toggle-navbar-item/', views.ajax_toggle_navbar_item, name='ajax_toggle_navbar_item'),

    # Videasy Player integration
    path('api/player/', views.videasy_player_view, name='videasy_player'),
    path('api/player/frame/', views.videasy_player_frame_view, name='videasy_player_frame'),
    path('proxy/<path:target>', views.proxy_view, name='videasy_proxy'),
    path('api/cookies', views.cookies_view, name='videasy_cookies'),
    path('api/health', views.health_view, name='videasy_health'),
    path('ajax/videasy-sources/', views.videasy_sources_view, name='videasy_sources'),
    path('api/series-extractor/', views.series_extractor_view, name='series_extractor'),
    path('ajax/player-sources/', views.player_sources_view, name='player_sources'),
    path('ajax/prefetch-sources/', streaming_views.prefetch_sources_view, name='prefetch_sources'),
    path('ajax/player-sources-stream/', streaming_views.player_sources_stream_view, name='player_sources_stream'),
    path('ajax/player-episodes/', views.player_episodes_view, name='player_episodes'),
    path('ajax/player-subtitles/', views.player_subtitles_view, name='player_subtitles'),
    path('collection/<int:collection_id>/', views.collection_detail, name='collection_detail'),
    path('person/<int:person_id>/', views.person_detail, name='person_detail'),
    path('trailer/<str:video_id>/', local_player.trailer_player, name='trailer_player'),
    path('trailer/stream/<str:video_id>/', local_player.trailer_stream, name='trailer_stream'),
    path('ajax/tmdb-extra/', views.tmdb_extra_ajax, name='tmdb_extra_ajax'),
    path('ajax/subscribe/', views.ajax_subscribe, name='ajax_subscribe'),
    path('unsubscribe/', views.unsubscribe_page, name='unsubscribe_page'),
    path('admin-dashboard/subscribers/', views.admin_subscribers, name='admin_subscribers'),
    path('ajax/send-email/', views.ajax_send_email, name='ajax_send_email'),
    path('about/', TemplateView.as_view(template_name='core/about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name='core/contact.html'), name='contact'),
    path('privacy/', TemplateView.as_view(template_name='core/privacy.html'), name='privacy'),
    path('terms/', TemplateView.as_view(template_name='core/terms.html'), name='terms'),
    path('sw.js', views.serve_sw_js, name='serve_sw_js'),
    path('sw-proxy.js', views.serve_sw_proxy_js, name='serve_sw_proxy_js'),
    path('ads.txt', views.serve_ads_txt, name='serve_ads_txt'),
    path('app-ads.txt', views.serve_app_ads_txt, name='serve_app_ads_txt'),
    path('admin-dashboard/ad-files/', views.admin_ad_files, name='admin_ad_files'),
    path('ajax/ad-files/save/', views.ajax_save_ad_file, name='ajax_save_ad_file'),
    path('ajax/ad-files/delete/', views.ajax_delete_ad_file, name='ajax_delete_ad_file'),
    path('admin-dashboard/users/', views.admin_user_list, name='admin_user_list'),
    path('admin-dashboard/users/add/', views.admin_user_add, name='admin_user_add'),
    path('admin-dashboard/users/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin-dashboard/users/<int:user_id>/edit/', views.admin_user_edit, name='admin_user_edit'),
    path('admin-dashboard/users/<int:user_id>/block/', views.admin_user_block, name='admin_user_block'),
    path('admin-dashboard/users/<int:user_id>/delete/', views.admin_user_delete, name='admin_user_delete'),
    path('admin-dashboard/users/<int:user_id>/subscription/', views.admin_user_subscription, name='admin_user_subscription'),
    path('admin-dashboard/settings/db-connections/', views.db_connection_settings, name='db_connection_settings'),
    path('admin-dashboard/settings/db-routing/', views.db_routing_settings, name='db_routing_settings'),
    path('admin-dashboard/settings/db-dashboard/', views.db_dashboard, name='db_dashboard'),
    path('ajax/test-db-connection-new/', views.ajax_test_db_connection, name='ajax_test_db_connection_new'),
    path('ajax/write-db-config/', views.ajax_write_db_config, name='ajax_write_db_config'),

    # Public pages: Providers & Watch Regions
    path('providers/', views.public_providers, name='public_providers'),
    path('watch-regions/', views.public_watch_regions, name='public_watch_regions'),
    path('ajax/toggle-user-providers/', views.ajax_toggle_user_providers, name='ajax_toggle_user_providers'),
    path('ajax/user-preferred-providers/', views.ajax_user_preferred_providers, name='ajax_user_preferred_providers'),

    # Page View & Time Tracking
    path('ajax/track-page-view/', views.ajax_track_page_view, name='ajax_track_page_view'),

    # Admin Analytics
    path('admin-dashboard/analytics/', views.admin_analytics, name='admin_analytics'),
    path('admin-dashboard/analytics/user/<int:user_id>/', views.admin_user_analytics_detail, name='admin_user_analytics_detail'),
]
